services:
  - type: web
    name: danat-shop
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: WEBAPP_URL
        sync: false
